name: Publish to Miun-Server

on:
    push:
        branches:
            - master

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Check out
              uses: actions/checkout@v1

            - name: Install Emacs
              uses: sudo apt install emacs-nox --yes

            - name: Build the site
              uses: ./build.sh

            - name: Publish generated content to Github pages
              uses: Oozna/github-pages-deplot-action@4.1.4
              with:
                branch: gh-pages
                folder: public
